prod:
  sfErrorNotifier:
    emailTo:      error@mysite.com  # EDIT THIS
    emailFrom:       # Optional, e.g.: My Site <no-reply@mysite.com> 
    emailFormat: html   # 'html' or 'txt', html by default 

 
