default:
  sf_error_notifier_plugin:
    enabled:         true                                          # Global enable or disable per env
    email_to:        me@localhost                                  # 
    email_from:      noreply@localhost
    email_format:    text/html                                     # 'text/html' or 'text/plain'
    email_subject:   "(%host%) [%environment%] %type%: %message%"  # Other options in sfErrorNotitifer.class.php
    report_errors:   true              # Notify for Symfony exceptions, and PHP errors
    report_warnings: false             # Notify for Symfony exceptions, and PHP warnings
    report_404:      false             # Also report 404 errors
